config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  resources :guesses, only: [:new, :create]

  resources :matches, only: [:show]

  namespace :api, defaults: { format: :json } do
    resources :winners, only: [:index]
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "sessions#new"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/guess.rb
class Guess < ApplicationRecord
  DISTANCE_FOR_SUCCESS = 1000

  belongs_to :match
  belongs_to :user

  validates :coord_x, :coord_y, numericality: true, presence: true
  validates :distance, numericality: true

  def self.new_with_coordenates(attributes)
    Guess.new(attributes).tap do |guess|
      guess.distance = guess.calculate_distance

      guess.is_successful = guess.calculate_success
    end
  end

  def calculate_distance
    return unless match && coord_x && coord_y

    Math.sqrt(
      (coord_x - match.treasure_x)**2 + (coord_y - match.treasure_y)**2
    ).round(2)
  end

  def calculate_success
    return unless distance

    distance <= DISTANCE_FOR_SUCCESS
  end
end

app/models/match.rb
class Match < ApplicationRecord
  MAX_COORD = 10_000

  validates :treasure_x, :treasure_y, numericality: { in: 0..MAX_COORD }, presence: true
  validates :closest_distance, numericality: true, allow_nil: true

  belongs_to :winner, class_name: 'User', optional: true, foreign_key: 'winner_id'
  has_many :guesses, dependent: :destroy

  def self.find_current_or_create_next
    Match.where(winner: nil).last || Match.create(
      treasure_x: Random.rand(MAX_COORD),
      treasure_y: Random.rand(MAX_COORD)
    )
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :email, presence: true

  has_many :guesses
end

app/controllers/api/api_controller.rb
class Api::ApiController < ApplicationController
  # This is a base class for all API controllers. It provides some common
  # functionality that all API controllers will need.

  before_action :authenticate!

  private

  def authenticate!
    return if request.headers['HTTP_API_KEY'] == Rails.application.credentials.api_key

    head :unauthorized
  end
end

app/controllers/api/winners_controller.rb
module Api
  class WinnersController < ApiController
    # GET /api/winners
    def index
      page_no = params[:page]&.to_i || 1
      per_page = 10
      order = params[:order] == 'desc' ? :desc : :asc

      @winners = User.select('users.id, users.email, MIN(guesses.distance) AS best_distance')
                     .joins(:guesses)
                     .where(guesses: { is_successful: true })
                     .group('users.id, users.email')
                     .offset((page_no - 1) * per_page)
                     .limit(per_page)
                     .order(best_distance: order, 'users.id': order)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :info

  helper_method :current_user

  protected

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def authenticate_user!
    redirect_to new_session_path unless current_user
  end
end

app/controllers/guesses_controller.rb
class GuessesController < ApplicationController
  before_action :authenticate_user!

  # GET /guesses/new
  def new
    @match = Match.find_current_or_create_next

    @last_guess = current_user.guesses.where(match: @match).last

    @guess = @match.guesses.build(coord_x: @last_guess&.coord_x, coord_y: @last_guess&.coord_y)
  end

  # POST /guesses
  def create
    MakeGuess.new(self).call(current_user, guess_params)
  end

  # See MakeGuess
  def match_has_already_finished(match)
    flash[:alert] = 'Match already finished'

    redirect_to match_path(match)
  end

  # See MakeGuess
  def invalid_request(guess)
    flash[:alert] = 'Invalid request. Please send both coordinates.'

    @guess = guess
    @match = guess.match
    @last_guess = current_user.guesses.where(match: guess.match).last

    render :new, status: :unprocessable_entity
  end

  # See MakeGuess
  def successful_guess(guess)
    guess.match.update(winner: guess.user)

    UserMailer.with(guess:).you_won.deliver_later

    flash[:notice] = 'Congratulations! You found the treasure!'

    redirect_to match_path(guess.match)
  end

  # See MakeGuess
  def unsuccessful_guess
    flash[:info] = 'Try again!'

    redirect_to new_guess_path
  end

  private

  def guess_params
    params.require(:guess).permit(:coord_x, :coord_y, :match_id)
  end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_action :authenticate_user!

  def show
    @match = Match.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    redirect_to new_guess_path if current_user
  end

  def create
    user = User.find_or_create_by(email: params[:email])

    session[:user_id] = user.id

    redirect_to new_guess_path
  end

  def destroy
    session.delete(:user_id)

    redirect_to new_session_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/guesses/new.html.erb
<div class="guess-container">
  <fieldset class="guess-fields">
    <legend>Match <%= @match.id %></legend>

    <%= form_for Guess.new do |f| %>
      <%= f.hidden_field :match_id, value: @match.id %>

      <div>
        <%= f.label :coord_x %>
        <%= f.number_field :coord_x, value: @guess.coord_x, step: 250, class: 'guess-fields__input' %>
      </div>

      <div>
        <%= f.label :coord_y %>
        <%= f.number_field :coord_y, value: @guess.coord_y, step: 250, class: 'guess-fields__input' %>
      </div>

      <%= f.submit 'Send coordenates', class: 'guess-fields__submit' %>
    <% end %>
  </fieldset>

  <% if @last_guess&.distance.present? %>
    <div class="current-distance">
      <h3>Last attempt:</h3>

      <p>Coord X: <%= @last_guess.coord_x %></p>
      <p>Coord Y: <%= @last_guess.coord_y %></p>
      <p>Distance: <%= @last_guess.distance %></p>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TreasureHunt</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="main-header">
      <h1>Treasure Hunt</h1>

      <% if current_user %>
        <div class="main-header__current-session">
          <div>Logged in as <%= current_user.email %>.</div>
          <div><%= button_to "Logout", sessions_path, method: :delete %></div>
        </div>
      <% end %>
    </div>

    <% if flash.any? %>
      <div>
        <% flash.each do |key, value| %>
          <div class="flash flash-<%= key %>"><%= value %></div>
        <% end %>
      </div>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/matches/show.html.erb
<h2>Match <%= @match.id %></h2>

<table class="ranking-table">
  <thead>
    <tr>
      <th>#</th>
      <th>User</th>
      <th>Distance</th>
    </tr>
  </thead>

  <% @match.guesses.order(distance: :asc).each_with_index do |guess, index| %>
    <tr>
      <td><%= index + 1 %></td>
      <td><%= guess.user.email %></td>
      <td><%= guess.distance %></td>
    </tr>
  <% end %>
</table>

<div class="play-again-fields">
  <%= link_to 'Play again!', new_guess_path %>
</div>